config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get  "/convites/busca" => "convites#busca"
  get  "/convidados/busca" => "convidados#busca"
  get  "/convidados/busca_com_filtro" => "convidados#busca_com_filtro"
  get  "/convidados/todos_convidados" => "convidados#todos_convidados"
  get  "/convidados/importar" => "convidados#importar_csv"
  post  "/convidados/importar" => "convidados#importar_csv"
  post  "/convidados/filtrar" => "convidados#filtrar"
  resources :convites
  resources :convidados
  root "convidados#index"
  
 
end

app/models/convidado.rb
class Convidado < ActiveRecord::Base
	has_one :convite
	validates :nome, presence: true, uniqueness: false, length: {maximum: 50}
	validates :bairro, presence: true

	def self.busca_total
		Convidado.where("convidados.id not in (select convidado_id from convites)").count()
	end

	def self.com_convite
		Convidado.where("convidados.id in (select convidado_id from convites)")
	end

	def self.sem_convite
		Convidado.where("convidados.id not in (select convidado_id from convites)")
	end

	def self.busca_com_filtro (filtro, valor)
		Convidado.where("#{filtro} like '#{valor}' and convidados.id not in (select convidado_id from convites)").order(:nome)
	end

	def self.descricao
		Convidado.sem_convite.select(:descricao).distinct.order(:descricao)
	end

	def self.cidade
		Convidado.sem_convite.select(:cidade).distinct.order(:cidade)
	end

	def self.bairro
		Convidado.sem_convite.select(:bairro).distinct.order(:bairro)
	end

	def self.importar(arquivo)
		CSV.foreach(arquivo.path, headers: true, encoding: "UTF-8") do |row|
			Convidado.create! row.to_hash
		end
	end
	
end

app/models/convite.rb
class Convite < ActiveRecord::Base
	belongs_to :user
	belongs_to :convidado

	def self.busca_total
		Convite.count()
	end
	

	def self.busca(nome_da_busca)
		
		#@convites=Convite.where('nome like ?', 'paulo').where_values_hash
		Convite.joins(:convidado).where("convidados.nome like '%#{nome_da_busca}%'")
		#@convites=Convite.where(convidado_id: "1")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :convite
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

      protected

          def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up, keys: [:usuario, :email, :password] )
              devise_parameter_sanitizer.permit(:account_update, keys:[:usuario, :email, :password, :current_password] )
          end
end

app/controllers/convidados_controller.rb
class ConvidadosController < ApplicationController

  before_action :set_convidado, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /convidados
  def index
    @convidados_sem_convite = Convidado.sem_convite.order(:nome)
    @convidados_bairro=Convidado.sem_convite.select(:bairro).distinct.order(:bairro)
    @total_convidados=Convidado.busca_total
    @total_convites=Convite.busca_total

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ConvidadosSemConvitePdf.new(@convidados_sem_convite)
        send_data pdf.render,type: "application/pdf",
                      disposition: "inline"
      end
    end
  end

  def todos_convidados
    @convidados= Convidado.all.order(:nome)
    @total_convidados=Convidado.all.count()

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ConvidadosPdf.new(@convidados,@total_convidados)
        send_data pdf.render,type: "application/pdf",
                      disposition: "inline"
      end
    end
  end

  # GET /convidados/1
  def show
  end
  
  def busca
    nome_a_buscar = "%#{params[:nome]}%"
    @convidados= Convidado.where("nome ILIKE ? or conjuge ILIKE ?", nome_a_buscar, nome_a_buscar).order(:nome)
    @total_convidados=@convidados.count()
    respond_to do |format|
      format.html {render :busca}
      format.json {render json: @convidados}
    end
    
  end

  def busca_com_filtro
    filtro= params[:filtro_selecionado]
    valor="%#{params[:valor_filtro]}%"
    @convidados_sem_convite=Convidado.busca_com_filtro(filtro, valor)
    @total_convidados=@convidados_sem_convite.count()
    render :index
  end


  def filtrar
    @opcao= params[:opcao_filtro]

    case @opcao
    when "descricao"
      @dados=Convidado.descricao()
    when "bairro"
      @dados=Convidado.bairro()
    when "cidade"
      @dados=Convidado.cidade()
    end

    respond_to do |format|
      #format.html {render :busca}
      format.json {render json: @dados}
    end
  end

  def importar_csv

    if params[:arquivo]
      #arquivo=params[:arquivo]
      Convidado.importar(params[:arquivo])
      redirect_to root_url, notice: "Convidados Importados com sucesso :)"
    else
      render :importar_csv
    end
    
  end

  # GET /convidados/new
  def new
    @convidado = Convidado.new
  end

  # GET /convidados/1/edit
  def edit

  end

  # POST /convidados
  def create
    @convidado = Convidado.new(convidado_params)

    if @convidado.save
      redirect_to new_convidado_path, notice: 'Convidado criado com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /convidados/1
  def update
    if @convidado.update(convidado_params)
      redirect_to convidados_path, notice: 'Convidado atualizado.'
    else
      render :edit
    end
  end

  # DELETE /convidados/1
  def destroy
    @convidado.destroy
    redirect_to convidados_url, notice: 'Convidado foi excluído com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convidado
      @convidado = Convidado.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def convidado_params
      params.require(:convidado).permit(:nome, :nome_no_convite, :conjuge, :endereco, :bairro, :cidade, :descricao)
    end
end

app/controllers/convites_controller.rb
class ConvitesController < ApplicationController
  before_action :set_convite, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /convites
  def index
    @convites = Convite.all
    @total_convites=Convite.busca_total

    respond_to  do |format|

      format.html
      format.pdf do
        pdf= ConvitesPdf.new(@convites)
        send_data pdf.render,type: "application/pdf",
                      disposition: "inline"
      end
    end
  end

  # GET /convites/1
  def show
  end

  def busca 
    nome_da_busca= params[:nome]
    @convites=Convite.busca(nome_da_busca)
    @total_convites=@convites.count()
    render :busca

  end
  # GET /convites/new
  def new
    @convite = Convite.new
    @convidados= Convidado.sem_convite

    if @convidados.count() <= 0
      redirect_to convites_path, notice: "Todos convidados cadastrados receberam convite."
    end
  end

  # GET /convites/1/edit
  def edit
  end

  # POST /convites
  def create
    data= Time.new
    convite= {:data_entrega => data, 
    :convidado_id => params["convidado_id"], 
    :user_id => current_user.id}

   @convite = Convite.new(convite)

      respond_to do |format|
         if @convite.save
            #format.html {redirect_to @convite, notice: 'Convite criado com sucesso.'}
            format.json {render json: '[{"notice": "Convite Criado com Sucesso"}]'}
        else
            format.html {render :teste}
            format.js {}
        end

    end
   
  end

  # PATCH/PUT /convites/1
  def update
    if @convite.update(convite_params)
      redirect_to @convite, notice: 'Convite atualizado com sucesso'
    else
      render :edit
    end
  end

  # DELETE /convites/1
  def destroy
    @convite.destroy
    redirect_to convites_url, notice: 'Convite removido com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convite
      @convite = Convite.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def convite_params
      params.require(:convite).permit(:data_entrega, :convidado_id, :user_id)
    end

    protect_from_forgery with: :null_session
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/convidados_helper.rb
module ConvidadosHelper
end

app/helpers/convites_helper.rb
module ConvitesHelper
end

app/views/convidados/busca.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-10 col-md-offset-1">
  <h1>Convidados Encontrados <span class="badge"><%=@total_convidados %></span></h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome Convidado</th>
        <th>Conjuge</th>
        <th>Descricao</th>
        <th colspan="3">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @convidados.each do |convidado| %>
        <tr>
          <td><%= convidado.nome %></td>
          <td><%= convidado.conjuge %></td>
          <td><%= convidado.descricao %></td>
          <td><%=  button_to 'Editar', edit_convidado_path(convidado), method: :get, class: 'btn btn-default btn-xs' %></td>
          <td>
            <%= button_to 'Excluir', convidado_path(convidado), method: :delete, 
            data: { confirm: 'Deseja realmente Excluir?' },
            class: 'btn btn-danger btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Novo Convidado', new_convidado_path %>

</div>

app/views/convidados/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3>Editar Convidado</h3>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
		<%= link_to 'Voltar', convidados_path %>
	</div>
	
</div>

app/views/convidados/importar_csv.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-10"><h3>Importar Convidados</h3></div>
<div class="col-md-offset-2 col-md-10">
		<%= form_tag convidados_importar_path, multipart: true do %>
			<div class="form-group">
			    <%= file_field_tag :arquivo, class: "col-md-5 control-label" %>
			    <div class="col-md-">
			      <%= submit_tag "Importar", class: "btn btn-default" %>
			    </div>
			</div>
		<% end %>
		
</div>
<div class="alert alert-success col-md-offset-2 col-md-6" style="margin-top: 1.2em;"role="alert">
	<p>O arquivo deve ser salvo com extensão .csv e com o seguinte cabeçalho: nome, conjuge, endereco, bairro, cidade e decricao.</p>
</div>

app/views/convidados/index.html.erb
 
  <div style="position:relative;" class="col-md-offset-1 col-md-10">
      <p id="notice"><%= notice %></p>
      <h1> Convidados sem Convite <span class="badge"><%= @total_convidados %></span> <i class="fa fa-search"></i> 
 </h1>
    <div class="col-md-12 div-filtro">
      <div class="col-md-2 col-md-offset-3">
        <label for="opcao_filtro"> Opção de filtro:</label>
      </div>
      <div class="col-md-3">
        <%= label_tag "opcao_filtro", "Bairro" %>
        <%= radio_button_tag "opcao_filtro", "bairro" %>
        <%= label_tag "opcao_filtro", "Descrição" %>
        <%= radio_button_tag "opcao_filtro", "descricao" %>
        <%= label_tag "opcao_filtro", "Cidade" %>
        <%= radio_button_tag "opcao_filtro", "cidade" %>
      </div>
       <%= form_tag convidados_busca_com_filtro_path, method: :get, class: "form-inline col-md-4 form-filtro" do %>
      <div class="form-group">
        <input type="hidden" name="filtro_selecionado" />
        <select name="valor_filtro" id="valor_filtro" class="form-control">     
        </select>
        <%= button_to "Filtrar", nil, class: "btn btn-primary" %>
      </div>    
    <% end %>
    </div>
       <table class="table table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Nome no Convite</th>
          <th>Conjuge</th>
          <th>Endereco</th>
          <th>Bairro</th>
          <th>Cidade</th>
          <th>Descricao</th>
          <th colspan="2">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @convidados_sem_convite.each do |convidado| %>
          <tr id="<%= convidado.id %>">
            <td><%= convidado.nome %></td>
            <td><%= convidado.nome_no_convite %></td>
            <td><%= convidado.conjuge %></td>
            <td><%= convidado.endereco %></td>
            <td><%= convidado.bairro %></td>
            <td><%= convidado.cidade %></td>
            <td><%= convidado.descricao %></td>
            <td><button name="convidar" class="btn btn-default btn-xs">Convidar</button></td>
            <td><%= button_to 'Editar', edit_convidado_path(convidado), method: :get, class: 'btn btn-default btn-xs' %></td>
            <td>
                <%= button_to 'Excluir', convidado_path(convidado), method: :delete, 
                data: { confirm: 'Deseja realmente Excluir?' },
                class: 'btn btn-danger btn-xs' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= button_to 'Novo Convidado', new_convidado_path, method: :get, class: 'btn btn-default' %>
  </div>
<% content_for :js do %>
 $(document).ready(function() {

  var convidado = function(){
    confirma= confirm("Deseja Registrar o Convite?");
    if(confirma){
      id = $(this).parent().parent().attr("id");
      convite = {convidado_id: id}
      $.ajax({
        url: "<%= convites_path %>",
        type: "POST",
        data: convite,
        success: function(data){
         location.reload();
      }

      });
    }
  }; 
  var filtrar = function(){
    var opcao= $(':checked').attr('value');
    $('input[name="filtro_selecionado"]').attr({value:opcao});
    $.ajax({
      url: "<%= convidados_filtrar_path %>",
      type: "POST",
      data: {opcao_filtro: opcao},
      success: function(data){
        var select= $('#valor_filtro');
        select.html('');
        $.each(data,function(i,obj){
            if(opcao=='bairro'){
              select.append("<option value='"+obj.bairro+"'>"+obj.bairro+"</option>");
            }
            else if(opcao=='cidade'){
              select.append("<option value='"+obj.cidade+"'>"+obj.cidade+"</option>");
            }
            else{
              select.append("<option value='"+obj.descricao+"'>"+obj.descricao+"</option>");
            }  
        });
      }
    });
  };

  var mostrar_div= function(){
    $('.div-filtro').toggle('slow');
  };
  $('button[name="convidar"]').bind('click', convidado);
  $('button[name="filtra_bairro"]').bind('click',filtrar);
  $('input[name="opcao_filtro"]').bind('click',filtrar);
  $('.fa-search').bind('click',mostrar_div);
 });
<% end %>

app/views/convidados/new.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-10"><h3>Novo Convidado</h3></div>
<div class="col-md-offset-2 col-md-10">
		<%= render 'form' %>
		<%= link_to 'Voltar', convidados_path %>
</div>
	


<% content_for :js do %>
	$(document).ready(function() {
		var sugestao= function(){
			palavras= $("#convidado_nome").val();
			$.ajax({
				url: "<%= convidados_busca_path %>",
				type: "GET",
				dataType: 'Json',
				data: {nome: palavras},
				success: function(data){
					if(palavras.length>0 && data.length){
					var lista = $("#lista");
					lista.html('');
					$("#sugestao").show('fast');
					$.each(data, function(i,obj){
						lista.append("<li class='item'>"+obj.nome+"</li>")
					});
					}
					else{
						$("#sugestao").hide('fast');
					}
					
				}
			});
		};
		$("#convidado_nome").bind('keyup', sugestao);
		$("#convidado_nome").focus();
	});
<% end %>

app/views/convidados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @convidado.nome %>
</p>

<p>
  <strong>Conjuge:</strong>
  <%= @convidado.conjuge %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @convidado.endereco %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @convidado.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @convidado.cidade %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @convidado.descricao %>
</p>

<%= link_to 'Edit', edit_convidado_path(@convidado) %> |
<%= link_to 'Back', convidados_path %>

app/views/convidados/todos_convidados.html.erb
<div class="col-md-12">
  <h1> Todos Convidados Cadastrados <span class="badge"><%= @total_convidados %></span></h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Conjuge</th>
        <th>Endereco</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Descricao</th>
     
      </tr>
    </thead>

    <tbody>
      <% @convidados.each do |convidado| %>
        <tr id="<%= convidado.id %>">
          <td><%= convidado.nome %></td>
          <td><%= convidado.conjuge %></td>
          <td><%= convidado.endereco %></td>
          <td><%= convidado.bairro %></td>
          <td><%= convidado.cidade %></td>
          <td><%= convidado.descricao %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to 'Novo Convidado', new_convidado_path, method: :get, class: 'btn btn-primary' %>
</div>

app/views/convites/busca.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-10">
  <h1>Convites Entregues <span class="badge"><%=@total_convites %></span></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome Convidado</th>
      <th>Data entrega</th>
      <th>Usuário</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @convites.each do |convite| %>
      <tr>
        <td><%= convite.convidado.nome %></td>
        <td><%= convite.data_entrega.strftime("%d/%m/%Y") %></td>
        <td><%= convite.user.usuario %></td>
        <td><%= link_to 'Show', convite %></td>
        <td><%= link_to 'Edit', edit_convite_path(convite) %></td>
        <td><%= link_to 'Destroy', convite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Convite', new_convite_path %>
</div>

app/views/convites/edit.html.erb
<h1>Editing Convite</h1>

<%= render 'form' %>

<%= link_to 'Show', @convite %> |
<%= link_to 'Back', convites_path %>

app/views/convites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data entrega:</strong>
  <%= @convite.data_entrega %>
</p>

<p>
  <strong>Convidado:</strong>
  <%= @convite.convidado_id %>
</p>

<%= link_to 'Edit', edit_convite_path(@convite) %> |
<%= link_to 'Back', convites_path %>

app/views/convites/teste.html.erb
<%= debug @convite%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Invitations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="shortcut icon" href="https://cdn3.iconfinder.com/data/icons/valenticons-2/64/valenticons-22-32.png" type="image/ico" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  .container{
  	/*background-color: #26ADE4;*/
  	margin: 5px auto;
  	width: 100%;
  }

  .navbar, .navbar-default{
  	margin-top: 5px;
  }

  .row{
  	padding: 10px;
  	/*background-color: #E1F5C4;*/
  	margin: 2px;
  	margin-bottom: 10px;
  	width: 100%;
  }
  #header{
  	background-color: #2C3E50;
  	margin-top: 0px;
  }

  #body{
  	/*background-color:  #F8F8F8;*/
  	border-radius: 4px;
  }

  .item{
  list-style-type: none;
  background-color: #F8F8F8;
  }

  /* css divs arredondadas */

  .circle {
margin-left: auto;
margin-right: auto;
border-radius: 50%;
width: 80%;
position: relative;
}

.circle-border {
border: 1px solid black;
}

.circle-solid{
background-color: whitesmoke;
}

.circle:before {
content: "";
display: block;
padding-top: 100%;
}

.circle-inner {
position: absolute;
top: 0;
left: 0;
bottom: 0;
right: 0;
text-align: center;
}

.score-text {
margin: auto;
position: absolute;
top: 0;
left: 0;
bottom: 0;
right: 0;
height: 1em;
line-height: 1em;
font-size: 1em;
}

#rodape{

}



#rodape p{

}


.container-fluid{
  background-color: #2C3E50;
  border-style: none;
  border-color: #2C3E50;
}

.navbar-default{
  border-style: none;
}

.navbar-default .navbar-brand {
	color: #FFF;
}

.navbar-default .navbar-nav > li > a{
	color: #FFF;
}

.navbar-default .navbar-brand:hover, .navbar-default .navbar-brand:focus{
	
	color: #FFF;
}
.navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus{
	color: #FFF;
	
}
.navbar-default .navbar-nav > .open > a, .navbar-default .navbar-nav > .open > a:hover, .navbar-default .navbar-nav > .open > a:focus {
	color: #FFF;
	background-color: #1A242F; 
}
.dropdown-menu{
	color: #FFF;
	background-color: #1A242F;
}
.dropdown-menu > li > a{
	color: #FFF;
}
.navbar-default .navbar-link{
	color: #FFF;
}

.col-md-12, .col-md-10, .login, .panel-default, .editar-perfil, .new_user {
	margin-top: 80px;
}

* {
	margin: 0;
	padding: 0;
}

html, body {
	height:100%;
}

.geral {
	min-height:100%;
	position:relative;
	width:100%;
}

#footer{
	position:absolute;
	bottom:0;
	width:100%;
	background-color: #222222;
	background-image: url("https://cdn3.iconfinder.com/data/icons/valenticons-2/64/valenticons-22-64.png");
	background-repeat: no-repeat;
	background-position: center;
	

}

#footer p{
	text-align: center;
	font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
	font-size: 16px;
	padding-top: 5px;
	color: #FFF;
}
#body {
	overflow:hidden;
	position: relative;
	padding-bottom: 80px;
}

.div-filtro{
	margin-top: 0px;
	padding: 1.2em;
	border: thin solid #2C3E50;
	box-shadow: 2px 2px 2px #2C3E50;
	display: none;
}

.div-filtro .form-filtro{
	text-align: right;
}

.radio-group{
	padding: 2px;
}

.fa-search{
	float: right;
	font-size: 16pt;
	margin-top: 1.0em;
	cursor: pointer;
}
.btn_pdf{
	float: left;
	margin: 1.2em;
}
  </style>
</head>
<body>
	<div class="geral">
			<div id="header" class="navbar navbar-default navbar-fixed-top">
				<div class="navbar navbar-default">
					<div class="container-fluid">
						<div class="navbar-header">
						      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						        <span class="sr-only">Toggle navigation</span>
						        <span class="icon-bar"></span>
						        <span class="icon-bar"></span>
						        <span class="icon-bar"></span>
						      </button>
						      <a class="navbar-brand" href="<%= root_url %>"><i class="fa fa-home fa-fw"></i>&nbsp;Home</a>
						    </div>

						    <!-- Collect the nav links, forms, and other content for toggling -->
						    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						      <ul class="nav navbar-nav">
						        <li> <a href="<%= root_url %>convidados"><i class="fa fa-users"></i> Convidados</a></li>
						        <li><a href="<%= root_url %>convites"><i class="fa fa-envelope-o"></i> Convites</a></li>
						        <li class="dropdown">
						          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Relatórios<span class="caret"></span></a>
						          <ul class="dropdown-menu">
						            <li><%= link_to "Todos Convidados", convidados_todos_convidados_path(format: "pdf"), method: :get %></li>
						            <li role="separator" class="divider"></li>
						            <li><%= link_to "Sem Convite",convidados_path(format: "pdf"), method: :get %></li>
						            <li role="separator" class="divider"></li>
						          </ul>
						        </li>
						         <li class="dropdown">
						          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu<span class="caret"></span></a>
						          <ul class="dropdown-menu">
						            <li><%= link_to "Registrar Convidados", new_convidado_path%></li>
						            <li><a href="<%= root_url %>">Registrar Convites</a></li>
						            <li role="separator" class="divider"></li>
						            <li><%= link_to "Todos Convidados", convidados_todos_convidados_path %></li>
						            <li role="separator" class="divider"></li>
						            <li><%= link_to "Importar convidados", convidados_importar_path, method: :get %></li>
						          </ul>
						        </li>
						      </ul>
						      <%= form_tag convidados_busca_path, method: :get, class: "navbar-form navbar-left"  do %>
						      	<div class="form-group">
						      		<%= text_field_tag :nome, nil, placeholder: "Buscar convidados", class: "form-control"%>
						      		<%= button_to "Buscar", nil, class: "btn btn-default" %>
						      	</div>		
						      <% end %>
						      <ul class="nav navbar-nav navbar-right">
						      	<% if user_signed_in? %>
							        <li class="dropdown">
							          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> <%= current_user.usuario %><span class="caret"></span></a>
							          <ul class="dropdown-menu">
							            <li><%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %></li>
							            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
							          </ul>
							        </li>
							    <% else %>
							    	 <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
		          					 <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
		          				<% end %>
						      </ul>
						    </div>
					</div>
				</div>
			</div>
			<div id="body" >
				<%= yield %>
				<script>
					<%= yield :js %>
				</script>
			</div>
			<div id="footer" class="col-md-12">
					<p style="">Mônica Caroline + Paulo Humberto</p>
					<p >14 de Janeiro de 2017</p>
			</div>

	</div>
</body>
</html>